### DISCUSSION TITLE
docker compose

### DISCUSSION THREAD

**Discussion by marcialwushu** [DevComputaria/Forum#104] [Listas]
```yml
# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: my-jenkins-3
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

```

**Comment by marcialwushu** [comment]
```yml
version: '3'
services:
    proxy:
        image: optaros/ssl-termination-proxy:latest
        container_name: ${PROJECT_PREFIX}_docker_termination_proxy
        ports:
            - "443:443"
        environment:
            HOST_IP: varnish
            PORT: 80
        networks:
            - magento2
        depends_on:
            - varnish
    varnish:
        image: (secret-company)
        container_name: ${PROJECT_PREFIX}_docker_varnish
        ports:
            - "80:80"
        environment:
            VIRTUAL_HOST: web
            VIRTUAL_PORT: 8080
            VIRTUAL_HOST_ASQATASUN: web
            VIRTUAL_PORT_ASQATASUN: 8085
        networks:
            - magento2
        depends_on:
            - web
    web:
        image: optaros/m2-docker-nginx
        container_name: ${PROJECT_PREFIX}_docker_web
        ports:
            - "8085:8080"
            - "8443:8443"
        volumes:
            - nfsmount:/var/www/html
            - sock:/sock
            - mediavol:/var/www/html/pub/media
        environment:
            - NGINX_HOST=${NGINX_HOST}
        tty: true
        links:
            - redis
            - php
        depends_on:
            - php
            - db
            - redis
            - media
        networks:
          - magento2
    php:
        image: optaros/m2-docker-php-fpm
        privileged: true
        container_name: ${PROJECT_PREFIX}_docker_php
        environment:
            PHP_IDE_CONFIG: serverName=${PHP_STORM}
            XDEBUG_CONFIG: idekey=PHPSTORM
            COMPOSER_HOME: /composer
            CONFIG__STORES__ADMIN__WEB__UNSECURE__BASE_URL: https://website-url.local/
            CONFIG__STORES__ADMIN__WEB__SECURE__BASE_URL: https://website-url.local/
            CONFIG__DEFAULT__WEB__UNSECURE__BASE_URL: https://website-url.local/
            CONFIG__DEFAULT__WEB__SECURE__BASE_URL: https://website-url.local/
            CONFIG__STORES__ADMIN__ADMIN__URL__CUSTOM_PATH: magentoadmin
            CONFIG__STORES__ADMIN__ADMIN__URL__USE_CUSTOM_PATH: 1
            CONFIG__STORES__DEFAULT__ADMIN__URL__USE_CUSTOM: 1
            CONFIG__STORES__DEFAULT__ADMIN__URL__CUSTOM: https://website-url.local/magentoadmin/
            CONFIG__DEFAULT__PCM__API__WSDL_URL: http://website-url.com/pcm-webservices/WebServicePCM.asmx?wsdl
            CONFIG__DEFAULT__DEV__STATIC__SIGN: 1
            CONFIG__DEFAULT__DEV__JS__MERGE_FILES: 0
            CONFIG__DEFAULT__DEV__JS__ENABLE_JS_BUNDLING: 1
            CONFIG__DEFAULT__DEV__CSS__MINIFY_FILES: 0
            CONFIG__DEFAULT__DEV__CSS__MERGE_CSS_FILES: 1
            CONFIG__DEFAULT__DEV__GRID__ASYNC_INDEXING: 1
        volumes:
            - ~/.ssh:/root/.ssh:cached
            - ~/.composer:/composer
            - nfsmount:/var/www/html
            - sock:/sock
            - mediavol:/var/www/html/pub/media
        links:
            - db
            - redis
        depends_on:
          - db
          - redis
          - media
        networks:
          - magento2
    db:
        image: (secret-company)/ndg-m2-docker-db:${ENVIRONMENT}
        container_name: ${PROJECT_PREFIX}_docker_db
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        networks:
          - magento2
    media:
        image: (secret-company)/ndg-m2-docker-media:${ENVIRONMENT}
        container_name: ${PROJECT_PREFIX}_docker_media
        volumes:
          - mediavol:/var/www/html/pub/media
    redis:
        image: redis:5.0.5
        container_name: ${PROJECT_PREFIX}_docker_redis
        env_file:
            - ".env"
        volumes:
            - redis:/data
        tty: true
        networks:
          - magento2
    rabbitmq:
        image: bitnami/rabbitmq:latest
        container_name: ${PROJECT_PREFIX}_docker_rabbitmq
        labels:
            kompose.service.type: nodeport
        ports:
            - '4369:4369'
            - '5672:5672'
            - '25672:25672'
            - '15672:15672'
        volumes:
            - 'rabbitmq_data:/bitnami'
        environment:
            - RABBITMQ_USERNAME=magento2
            - RABBITMQ_PASSWORD=magento2
            - RABBITMQ_VHOST=magento2
        networks:
          - magento2
    mailhog:
      container_name: ${PROJECT_PREFIX}_docker_mailhog
      image: mailhog/mailhog:v1.0.0
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
        - magento2
#    elasticsearch:
#        image: elasticsearch:1.7
#        container_name: ${PROJECT_PREFIX}_docker_elasticsearch
#        restart: always
#        ports:
#          - 9200
#          - 9300
volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":PROJECT_DIR"
    mediavol: {}
    redis: {}
    rabbitmq_data:
        driver: local
    mysql:
    sock:

networks:
  magento2:
    driver: bridge

```
